### ISSUE TITLE
[Bug] Helm chart refers to non-existent temporalio/maru image

### ISSUE THREAD

**Issue by GreyTeardrop** [temporalio/maru#24]
**Describe the bug**
Maru's Helm chart refers to the `temporalio/maru` container image. However, that image does not exist.

**Expected behavior**
I would expect either for that image to exist, or to be replaced with a "stub" image name that obviously does not exist if it's expected that every consumer should build their own image.

**Comment by mikhailshilkov** [comment]
Good point! For now, my intention was the latter (every consumer should build their own image). What would a good stub image name be? Mind opening a PR?

**Comment by GreyTeardrop** [comment]
> Good point! For now, my intention was the latter (every consumer should build their own image). What would a good stub image name be? Mind opening a PR?

Maybe something like `<your-maru-image>`? I can open a PR if that's ok.

I initially thought that a ready-made Maru image might be useful in some cases. In the scenario of my team, we'll be running workloads implemented with Java SDK, so we'll be uploading a stock Maru image and will run a separate JVM-based worker with the actual workflows and activities we plan to performance test.

**Comment by mikhailshilkov** [comment]
That makes sense!

Let's do the `<your-maru-image>` change for now and then I'll take a look at publishing an official image for releases.

**Comment by GreyTeardrop** [comment]
I've opened up https://github.com/temporalio/maru/pull/25 and marked it to fix this issue.

**Comment by mikhailshilkov** [comment]
Thank you! I opened https://github.com/temporalio/maru/issues/26 to follow-up
